-- Baseline schema for the transaction monitoring system.
-- Column names match the JPA entities under the default Spring Boot
-- (CamelCaseToUnderscores) naming strategy. Money is numeric(19,2).

CREATE TABLE transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type               VARCHAR(255)   NOT NULL,
    amount             NUMERIC(19, 2) NOT NULL,
    old_balance_orig   NUMERIC(19, 2) NOT NULL,
    new_balance_orig   NUMERIC(19, 2) NOT NULL,
    old_balance_dest   NUMERIC(19, 2) NOT NULL,
    new_balance_dest   NUMERIC(19, 2) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE risk_scores (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   BIGINT        NOT NULL UNIQUE REFERENCES transactions (id),
    score            INTEGER       NOT NULL,
    risk_level       VARCHAR(255),
    triggered_rules  VARCHAR(1000),
    scored_at        TIMESTAMP WITH TIME ZONE
);

CREATE TABLE alerts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     BIGINT        NOT NULL UNIQUE REFERENCES transactions (id),
    risk_score_id      BIGINT        NOT NULL UNIQUE REFERENCES risk_scores (id),
    status             VARCHAR(255),
    investigator_note  VARCHAR(2000),
    created_at         TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_alerts_status ON alerts (status);
CREATE INDEX idx_alerts_created_at ON alerts (created_at);
