-- Audit trail: one row per alert status change, recording who did it and when.
-- This is what turns the review workflow into an accountable, compliance-style
-- log ("who resolved this alert, when, and why").

CREATE TABLE alert_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id     BIGINT       NOT NULL REFERENCES alerts (id),
    from_status  VARCHAR(255),
    to_status    VARCHAR(255) NOT NULL,
    note         VARCHAR(2000),
    actor        VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_alert_events_alert_id ON alert_events (alert_id);
